# Generated by Django 5.2.1 on 2025-06-06 23:28

import os

from django.db import migrations
from django.utils import timezone


def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists():
        return

    username = os.environ.get("DJANGO_SUPERUSER_USERNAME")
    email = os.environ.get("DJANGO_SUPERUSER_EMAIL")
    password = os.environ.get("DJANGO_SUPERUSER_PASSWORD")

    if not all([username, email, password]):
        # You could raise an error or just return if env vars are missing
        return

    superuser = User.objects.create_superuser(
        username=username,
        email=email,
        password=password,
        last_login=timezone.now(),
    )
    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_superuser)]
