# Generated by Django 5.2.1 on 2025-06-10 14:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, validators=[app.models.validate_youtube_url]),
        ),
    ]
