# Generated by Django 5.2.1 on 2025-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_videoplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Classical', 'Classical'), ('Electronic', 'Electronic'), ('Jazz', 'Jazz'), ('Folk', 'Folk'), ('Hip-Hop / Rap', 'Hip-Hop / Rap'), ('Soul', 'Soul'), ('Country', 'Country'), ('World / Regional', 'World / Regional'), ('Other', 'Other')], db_index=True, default='Hip-Hop / Rap', max_length=20),
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trackplay',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videoplay',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
