# Generated by Django 5.2.1 on 2025-07-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='latitude',
            field=models.FloatField(blank=True, help_text="The latitude of the artist's location.", null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='location_name',
            field=models.CharField(blank=True, help_text='e.g., Rocinha, Rio de Janeiro', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='longitude',
            field=models.FloatField(blank=True, help_text="The longitude of the artist's location.", null=True),
        ),
    ]
