"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import config
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file located at the project root
# This loads a base .env file if it exists.
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Load environment-specific .env files based on an explicit ENVIRONMENT variable.
# Normalize to lowercase after stripping any surrounding whitespace.
ENVIRONMENT = os.environ.get("ENVIRONMENT", "").strip().lower()

if ENVIRONMENT == "local":
    # If ENVIRONMENT is 'local', load .env.local and allow it to override existing variables.
    load_dotenv(os.path.join(BASE_DIR, ".env.local"), override=True)
elif ENVIRONMENT == "prod":
    # If ENVIRONMENT is 'docker', load .env.docker and allow it to override existing variables.
    load_dotenv(os.path.join(BASE_DIR, ".env.docker"), override=True)
# You can add more 'elif' blocks here for other environments like 'production', 'staging', etc.

# After the above steps, your Django settings can safely access environment variables
# using os.environ.get('YOUR_VARIABLE_NAME').


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1k0rswl8wlff&ov#7n@7kbk(+0453tpsre-gj(w!_+n2ye+8ey"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend"  # Default backend
]


TAILWIND_APP_NAME = "theme"

# Application definition

# settings.py

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    "django_extensions",
    "tailwind",
    "theme",
    "django_browser_reload",
    "widget_tweaks",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "anymail",
]

PROJECT_APPS = [
    "app.apps.AppConfig",  # Replace with your actual app config if different
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]

    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

    import socket

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())

    INTERNAL_IPS = [ip[:-1] + "1" for ip in ips] + ["127.0.0.1"]
    INTERNAL_IPS += [
        "192.168.65.1",
    ]


ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file located at the project root
# This loads a base .env file if it exists.
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Load environment-specific .env files based on an explicit ENVIRONMENT variable.
# Normalize to lowercase after stripping any surrounding whitespace.
ENVIRONMENT = os.environ.get("ENVIRONMENT", "").strip().lower()

if ENVIRONMENT == "local":
    # If ENVIRONMENT is 'local', load .env.local and allow it to override existing variables.
    load_dotenv(os.path.join(BASE_DIR, ".env.local"), override=True)
elif ENVIRONMENT == "prod":
    # If ENVIRONMENT is 'docker', load .env.docker and allow it to override existing variables.
    load_dotenv(os.path.join(BASE_DIR, ".env.docker"), override=True)
# You can add more 'elif' blocks here for other environments like 'production', 'staging', etc.

# After the above steps, your Django settings can safely access environment variables
# using os.environ.get('YOUR_VARIABLE_NAME').


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1k0rswl8wlff&ov#7n@7kbk(+0453tpsre-gj(w!_+n2ye+8ey"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend"  # Default backend
]


TAILWIND_APP_NAME = "theme"

# Application definition

# settings.py

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    "django_extensions",
    "tailwind",
    "theme",
    "django_browser_reload",
    "widget_tweaks",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "anymail",
]

PROJECT_APPS = [
    "app.apps.AppConfig",  # Replace with your actual app config if different
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]

    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

    import socket

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())

    INTERNAL_IPS = [ip[:-1] + "1" for ip in ips] + ["127.0.0.1"]
    INTERNAL_IPS += [
        "192.168.65.1",
    ]


ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"), conn_max_age=600
    )
}

# Custom User Model
AUTH_USER_MODEL = "app.UserProfile"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "account_login"

# Allauth settings

ACCOUNT_LOGIN_METHODS = {"email", "username"}


ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]


# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Ensure this is set to mandatory
SITE_ID = 1  # Essential for allauth to build correct verification links

# --- django-anymail and SendGrid API Configuration ---
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"  # This tells Django to use Anymail for SendGrid
ANYMAIL = {
    "SENDGRID_API_KEY": config("SENDGRID_API_KEY"),  # Reads the key from your .env file
}
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")  # Your verified sending email
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Good practice for error emails


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "theme/static",  # Points to 'static'
    BASE_DIR / "theme/static_src/src",  # Points to 'src'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom User Model
AUTH_USER_MODEL = "app.UserProfile"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "account_login"

# Allauth settings

ACCOUNT_LOGIN_METHODS = {"email", "username"}


ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]


# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Ensure this is set to mandatory
SITE_ID = 1  # Essential for allauth to build correct verification links

# --- django-anymail and SendGrid API Configuration ---
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"  # This tells Django to use Anymail for SendGrid
ANYMAIL = {
    "SENDGRID_API_KEY": config("SENDGRID_API_KEY"),  # Reads the key from your .env file
}
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")  # Your verified sending email
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Good practice for error emails


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "theme/static",  # Points to 'static'
    BASE_DIR / "theme/static_src/src",  # Points to 'src'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
